.PHONY: clean All

All:
	@echo "----------Building project:[ USB_Serial - Debug ]----------"
	@cd "USB_Serial" && "$(MAKE)" -f  "USB_Serial.mk"
clean:
	@echo "----------Cleaning project:[ USB_Serial - Debug ]----------"
	@cd "USB_Serial" && "$(MAKE)" -f  "USB_Serial.mk" clean
